[build]
  command = "npm install && npm run build"
  commandOrigin: config
  publish = "/opt/build/repo/dist"
  publishOrigin: config
functionsDirectory: /opt/build/repo/backend

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200