[build]
  command = "npm install && npm run build"
  publish = "/opt/build/repo/dist"

[functions]
  directory = "/opt/build/repo/backend"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200